---
- name: COMMAND | Check if system is a VM
  ansible.builtin.command: systemd-detect-virt
  register: systemd_detect_virt
  changed_when: false

- name: FACT | is_vm = true
  ansible.builtin.set_fact:
    is_vm: true
  when: systemd_detect_virt.rc == 0

- name: FACT | is_vm = false
  ansible.builtin.set_fact:
    is_vm: false
  when: systemd_detect_virt.rc != 0

- ansible.builtin.include_tasks: '{{ item }}'
  loop:
  - repositories.yml
  - packages.yml

- name: SHELL | Check for battery in the system
  ansible.builtin.shell: ls /sys/class/power_supply/ | grep -q 'BAT'
  register: battery_check
  changed_when: false

- ansible.builtin.include_tasks: laptop.yml
  when: battery_check.rc == 0
