---
- name: APT | Install apt packages (CLI)
  ansible.builtin.apt:
    state: present
    name: '{{ cli_pkg }}'
  loop:
    - curl
    - debian-goodies
    - git
    - git-extras
    - libimage-exiftool-perl # exiftool tool edit image metadata. Dolphin integration: https://github.com/Merrit/kde-dolphin-remove-metadata
    - keychain # Manager for ssh-agent
    - neovim
    - python-is-python3
    - tmux
    - vim
    - zsh
  loop_control:
    loop_var: cli_pkg

- name: APT | Install apt packages (Desktop)
  ansible.builtin.apt:
    state: present
    name: '{{ desktop_pkg }}'
  loop:
    - 1password
    - code
    - flatpak
  loop_control:
    loop_var: desktop_pkg
  when: workstation_environment == "Desktop"

- name: SHELL | Check for KDE Plasma Desktop Environment
  shell: echo $XDG_CURRENT_DESKTOP
  register: desktop_env
  changed_when: false

- name: APT | Install apt packages (KDE)
  ansible.builtin.apt:
    state: present
    name: '{{ kde_pkg }}'
  loop:
    - plasma-discover-backend-flatpak
  loop_control:
    loop_var: kde_pkg
  when:
    - workstation_environment == "Desktop"
    - '"KDE" in desktop_env.stdout'

- name: FLATPAK_REMOTE | Add flathub flatpak repository
  community.general.flatpak_remote:
    name: flathub
    flatpakrepo_url: https://dl.flathub.org/repo/flathub.flatpakrepo
  when: workstation_environment == "Desktop"

- name: FLATPAK | Install flatpak packages
  community.general.flatpak:
    name:
      - md.obsidian.Obsidian
  when: workstation_environment == "Desktop"
