---
- name: APT | Install apt packages (CLI)
  ansible.builtin.apt:
    state: present
    name: '{{ cli_pkg }}'
  loop:
    - curl
    - debian-goodies
    - git
    - git-extras
    - neovim
    - tmux
    - vim
    - zsh
  loop_control:
    loop_var: cli_pkg

- name: APT | Install apt packages (Desktop)
  ansible.builtin.apt:
    state: present
    name: '{{ desktop_pkg }}'
  loop:
    - 1password
    - code
    - flatpak
  loop_control:
    loop_var: desktop_pkg
  when: workstation_environment == "Desktop"

- name: FLATPAK_REMOTE | Add flathub flatpak repository
  community.general.flatpak_remote:
    name: flathub
    flatpakrepo_url: https://dl.flathub.org/repo/flathub.flatpakrepo
  when: workstation_environment == "Desktop"

- name: FLATPAK | Install flatpak packages
  community.general.flatpak:
    name:
      - md.obsidian.Obsidian
  when: workstation_environment == "Desktop"
