---
- name: Install apt packages (CLI)
  ansible.builtin.apt:
    state: present
    name:
      - curl
      - debian-goodies
      - git
      - git-extras
      - neovim
      - tmux
      - vim
      - zsh
  when: workstation_environment == "CLI"

- name: Install apt packages (Desktop)
  ansible.builtin.apt:
    state: present
    name:
      - 1password
      - code
  when: workstation_environment == "Desktop"

- name: Add flathub flatpak repository
  community.general.flatpak_remote:
    name: flathub
    flatpakrepo_url: https://dl.flathub.org/repo/flathub.flatpakrepo
  when: workstation_environment == "Desktop"

- name: Install flatpak packages
  community.general.flatpak:
    name:
      - md.obsidian.Obsidian
  when: workstation_environment == "Desktop"
