---
- name: Install apt packages
  apt:
    name: '{{ item }}'
    state: present
  loop:
    - 1password
    - code
    - curl
    - debian-goodies
    - flatpak
    - git
    - git-extras
    - gnome-tweaks
    - neovim
    - tmux
    - vim
    - zsh

- name: Add flathub flatpak repository
  community.general.flatpak_remote:
    name: flathub
    flatpakrepo_url: https://dl.flathub.org/repo/flathub.flatpakrepo

- name: Install flatpak packages
  community.general.flatpak:
    name: '{{ item }}'
  loop:
    - md.obsidian.Obsidian
