---
# After installation, Debian retains CDROM entries in APT. They should be removed.
- name: LINEINFILE | Remove cdrom entries in /etc/apt/sources.list
  ansible.builtin.lineinfile:
    path: /etc/apt/sources.list
    state: absent
    regexp: '^deb cdrom'
  notify: Update Apt

- name: SET_FACT | Defaults
  ansible.builtin.set_fact:
    workstation_gpg_keys_cli: []
    workstation_gpg_keys_desktop: []
    workstation_ascii_armor_key_cli: []
    workstation_ascii_armor_key_desktop: []
    workstation_apt_repositories_cli: []
    workstation_apt_repositories_desktop: []

- name: SET_FACT | Third-party gpg keys (CLI)
  ansible.builtin.set_fact:
    workstation_gpg_keys_cli: []
  when: workstation_environment == "CLI"

- name: SET_FACT | Third-party gpg keys (Desktop)
  ansible.builtin.set_fact:
    workstation_gpg_keys_desktop:
      - { name: 'brave-browser', url: 'https://brave-browser-apt-release.s3.brave.com/brave-browser-archive-keyring.gpg' }
  when: workstation_environment == "Desktop"

- name: GET_URL | Add gpg keys for extra repositories
  ansible.builtin.get_url:
    url: '{{ gpg_key.url }}'
    dest: /usr/share/keyrings/{{ gpg_key.name }}-archive-keyring.gpg
  loop: "{{ workstation_gpg_keys_cli + workstation_gpg_keys_desktop }}"
  loop_control:
    loop_var: gpg_key

- name: SET_FACT | Third-party ASCII-armored gpg keys (CLI)
  ansible.builtin.set_fact:
    workstation_ascii_armor_key_cli: []
  when: workstation_environment == "CLI"

- name: SET_FACT | Third-party ASCII-armored gpg keys (Desktop)
  ansible.builtin.set_fact:
    workstation_ascii_armor_key_desktop:
      - { name: '1password', url: 'https://downloads.1password.com/linux/keys/1password.asc' }
      - { name: 'microsoft', url: 'https://packages.microsoft.com/keys/microsoft.asc' }
  when: workstation_environment == "Desktop"

- name: SHELL | Add ASCII-armored gpg keys for extra repositories
  ansible.builtin.shell:
    cmd: wget -qO- {{ ascii_gpg_key.url }} | gpg --dearmor --output {{ ascii_gpg_key.name }}-archive-keyring.gpg
    chdir: /usr/share/keyrings
    creates: /usr/share/keyrings/{{ ascii_gpg_key.name }}-archive-keyring.gpg
  loop: "{{ workstation_ascii_armor_key_cli + workstation_ascii_armor_key_desktop }}"
  loop_control:
    loop_var: ascii_gpg_key

- name: SET_FACT | Third-party apt repositories (CLI)
  ansible.builtin.set_fact:
    workstation_apt_repositories_cli: []
  when: workstation_environment == "CLI"

- name: SET_FACT | Third-party apt repositories (Desktop)
  ansible.builtin.set_fact:
    workstation_apt_repositories_desktop:
      - { name: '1password', gpgkey: '1password', url: 'https://downloads.1password.com/linux/debian/amd64 stable main' }
      - { name: 'brave-browser-release', gpgkey: 'brave-browser', url: 'https://brave-browser-apt-release.s3.brave.com/ stable main' }
      - { name: 'vscode', gpgkey: 'microsoft', url: 'https://packages.microsoft.com/repos/code stable main' }
  when: workstation_environment == "Desktop"

- name: APT_REPOSITORY | Add third-party apt repositories
  ansible.builtin.apt_repository:
    filename: '{{ repo.name }}'
    repo: 'deb [arch=amd64 signed-by=/usr/share/keyrings/{{ repo.gpgkey }}-archive-keyring.gpg] {{ repo.url }}'
  loop: "{{ workstation_apt_repositories_cli + workstation_apt_repositories_desktop }}"
  loop_control:
    loop_var: repo
  notify: Update Apt

# Flush handlers so we make sure to update apt before installing packages
- name: Flush handlers
  meta: flush_handlers
